/****************************************************************************************
ncSQLInstanceDataPoint.h
	Copyright (c)  Eisoo Software Inc. (2004-2013), All right reserved

PursePose:
	header file for Oracle Backup Exception

Author:
	huang.kaide@eisoo.com
Created Time:
	2013-7-15
***************************************************************************************/
#ifndef _NC_ORACLE_BACKUP_EXCEPTION_H_
#define _NC_ORACLE_BACKUP_EXCEPTION_H_

#include <ncutil.h>
#include <ncAppException.h>

////////////////////////////////////////////////////////////////////////////////////////////////////////
//错误及异常类的声明及定义
////////////////////////////////////////////////////////////////////////////////////////////////////////
#define NC_ORACLE_BACK_ERROR_PROVIDER_NAME _T("oracleBackup")

/**
 * 定义错误类异常
 */
#define THROW_ORACLE_BACKUP_ERROR(msg, errorID)                 \
	NC_THROW_ROOT_EXPT_BY_MSG(ncOracleBackupErrorException, msg, errorID, ::ncGetOracleBACKUPErrorProvider ());

/*
 * 根据捕获异常值来抛异常
 */
#define THROW_ORACLE_BACKUP_ERROR_WITH_CAUSE(msg, e, errorID)	\
	NC_THROW_ROOT_EXPT_BY_MSG_WITH_CAUSE(ncOracleBackupErrorException, msg, e, errorID, ::ncGetOracleBACKUPErrorProvider());

/**
 * 定义警告类异常
 */
#define THROW_ORACLE_BACKUP_WARNING(msg, errorID)               \
	NC_THROW_ROOT_EXPT_BY_MSG(ncOracleBackupWarnException, msg, errorID, ::ncGetOracleBACKUPErrorProvider ());

/**
 * 错误提供者
 */
static ncCoreErrorProvider* oracleBackupErrorProvider = 0;

/**
 * 获取错误提供者
 */
inline IErrorProvider*
ncGetOracleBACKUPErrorProvider (void)
{
	if (oracleBackupErrorProvider == 0) {
		oracleBackupErrorProvider = new ncCoreErrorProvider (NC_ORACLE_BACK_ERROR_PROVIDER_NAME);
	}

	return oracleBackupErrorProvider;
}

DECLARE_APP_EXCEPTION(ncOracleBackupErrorException, ncCoreAbortException)
DECLARE_APP_EXCEPTION(ncOracleBackupWarnException, ncCoreWarnException)
/*****************************************************************************
 * 定义 TBE 异常
 */

#define MAKE_ORACLE_BACK_ERROR_NUM(expClass, value)	\
	MAKE_ERROR_NUMBER(expClass, ORACLE_SINGLE_BACKUP_EXCEPTION_MODULE, value)

//ORACLESchedule Error 0x1~0x7FFF
//ncOracleBackupExec.cpp
#define ERROR_CREATE_PUSH_STREAM_REACTOR_FAILED                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0001)
#define ERROR_CREATE_RESOURCE_MANAGER_FAILED                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0002)
#define ERROR_ORACLE_DATASOURCE_NOT_ONE                             MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0003)
#define ERROR_CREATE_ORACLE_CID_OBJECT_ERROR                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0004)
#define ERROR_CREATE_ORACLE_EXTENSION_OBJECT_ERROR                  MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0005)
#define ERROR_CREATE_ORACLE_TIMEPOINT_OBJECT_ERROR                  MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0006)
#define ERROR_CREATE_ORACLE_DATA_OBJECT_FAILED                      MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0007)
#define ERROR_CREATE_ORACLE_DATA_BLOCK_FAILED                       MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0008)

//ncOracleBackupSchedule.cpp
#define ERROR_ORACLE_BACKUP_EXCEPTION                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0009)
#define ERROR_ORACLE_BACKUP_UNKOWN_EXCEPTION                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x000A)
#define ERROR_GET_LISTENER_NULL                                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x000B)

//ncOracleDatabasebManager.cpp
#define ERROR_CREATE_ORACLE_MANAGER_FAILED			                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x000C)
#define ERROR_CREATE_PFILE_FAILED                                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x000D)
#define ERROR_ORACLE_STATUS_NOT_OPEN                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x000E)
#define ERROR_ORACLE_NOT_ARCHIVELOG_MODE                            MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x000F)
#define ERROR_ORACLE_ARCHIVE_DEST_FLASHBACK_AREA                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0010)
#define ERROR_ORACLE_ARCHIVE_ILLEGAL                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0011)
#define ERROR_DATABASE_OPEN_CANNOT_RESTORE                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0012)
#define ERROR_DATABASE_NOT_STARTRD_STATUS							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0013)
#define ERROR_DATABASE_NOT_MOUNTED_STATUS							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0014)
#define ERROR_DATABASE_OPEN_CANNOT_RESTORE_DATAFILE                 MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0015)
#define ERROR_ORACLE_TABLE_IMP_FAILED                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0016)
#define ERROR_ORACLE_TABLE_EXSIT_IN_PRODUCTION_DB					MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0017)
#define ERROR_AUX_DATABASE_STATUS_NOT_NOMOUNT						MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0018)
#define ERROR_AUX_DATABASE_STATUS_NOT_OPEN                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0019)
#define ERROR_ORACLE_INPUT_DATAFILE_ERROR							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x001A)
#define ERROR_ORACLE_READ_USER_CONFIG			            	    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0101)

//ncOracleRestoreSchedule.cpp
#define ERROR_ORACLE_RESTORE_EXCEPTION                              MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x001B)
#define ERROR_ORACLE_RESTORE_UNKOWN_EXCEPTION                       MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x001C)
#define ERROR_ORACLE_DIRECTORY_NOT_EXSIT							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x001D)

//ncOracleRestoreExec.cpp
#define ERROR_ORACLE_RESTORE_CTRL_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x001E)
#define ERROR_ORACLE_TIME_RESTORE_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x001F)

//ncOracleCtrlFilePopEvent.cpp
#define ERROR_ORACLE_RESTORE_DATA_EMPTY						        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0020)
#define ERROR_ORACLE_WRITE_ARCH_FAILED							    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0021)

//ncOraclePopEvent.cpp
#define ERROR_ORACLE_RESTORE_GNS_NOEXIST							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0022)

//#ncOracleExecThread.cpp
#define ERROR_START_RMAN_EXE_NOKNOWN_ERROR                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0023)
#define ERROR_CREATE_RMAN_OUTPUT_PIPE_FAILED                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0024)
#define ERROR_CREATE_RMAN_EXE_PROCESS_FAILED                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0025)
#define ERROR_RMAN_EXITED_SCHEDULE_WILL_STOPED                      MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0026)
#define ERROR_ORACLE_RMAN_OUTPUT_FAILED								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0027)
#define ERROR_ORACLE_ARC_NOT_FIND_IN_BACKUP_PICES                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0028)
#define ERROR_ORACLE_ERROR_RMAN_06056								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0029)
#define	ERROR_ORACLE_BEFORE_RESETLOG_TIME							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002A)
#define ERROR_ORACLE_RMAN_OUTPUT_THREAD_UNKOWN_ERROR				MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002B)
#define ERROR_ORACLE_ERROR_RMAN_06026								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002C)
#define ERROR_ORACLE_READ_USER_CONFIG_TRACE			            	MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0102)

//ncOracleScheduleCommon.cpp
#define ERROR_ORACLE_DATASOURCE_NOT_EXSIT							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002C)
#define ERROR_ORACLE_RESTORE_ARCHIVE_PATH_NOLEGAL                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002D)
#define ERROR_GET_ARCHIVE_DEST_USER_FAILED                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002E)
#define ERROR_ORACLE_ARCHIVE_DEST_USER_ROOT							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x002F)

//ncRmanDataManager.cpp
#define ERROR_ORACLE_CREATE_SVRPIPE_FAILED                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0030)
#define ERROR_ORACLE_CREATE_EVENTS_FAILED                           MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0031)
#define ERROR_CLIENT_ORACLE_PIPE_CONNECT_FAILED                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0032)
#define ERROR_RECEIVE_SBTINIT_MSG_FAILED                            MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0033)
#define ERROR_RECEIVE_PID_VALUE_FAILED                              MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0034)
#define ERROR_RECEIVE_PID_MSG_FAILED                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0035)
#define ERROR_PID_MSG_OVER_FAILED                                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0036)
#define ERROR_RECEIVE_NEWSET_OR_BAKEND_MSG_FAILED                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0037)
#define ERROR_RECEIVE_NEWSET_FILEMSG_FAILED                         MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0038)
#define ERROR_RECEIVE_BLOCK_SIZE_FAILED								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0039)
#define ERROR_RECEIVE_NEWSET_OR_BAKEND_MSG_ERROR                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x003A)
#define ERROR_RECEIVE_DATASIZE_ORA_ENDSET_MSG_FAILED                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x003B)
#define ERROR_RECEIVE_DATASIZE_DATABLOCK_FAILED                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x003C)
#define ERROR_RECEIVE_DATASIZE_ENDSET_ERROR                         MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x003D)
#define ERROR_ORACLE_RESTORE_READ_FILE_EMPTY                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x003E)
#define ERROR_ORACLE_RECEIVE_BLOCK_SIZE_FAILED						MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x003F)
#define ERROR_ORACLE_RECEIVE_SBT_RESTORE_OVER_FAILED                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0040)
#define ERROR_ORACLE_RECEIVE_STILL_DATA_MSG_FAILED					MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0041)
#define ERROR_ORACLE_SEND_DATASIZE_FAILED                           MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0042)
#define ERROR_RECEIVE_BAKEND_MSG_INCONSISTENT						MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0043)
#define ERROR_ORACLE_SEND_ENDSET_FAILED								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0044)
#define ERROR_ORACLE_RECEIVE_ENDSET_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0045)
#define ERROR_ORACLE_RECEIVE_STILL_DATA_OR_ORA_ENDSET_FAILED        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0046)
#define ERROR_RECEIVE_BACKEND_MSG_FAILED                            MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0047)
#define ERROR_RECEIVE_CLOSEPIPE_MSG_FAILED                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0048)
#define ERROR_SEND_CLOSE_PIPE_FAILED                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0049)
#define ERROR_RECEIVE_MSG_FAILED                                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004A)
#define ERROR_SEND_CROSSCHECK_MSG_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004B)
#define ERROR_RECEIVE_CROSSCHECK_MSG_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004C)
#define ERROR_RECEIVE_PIECE_NAME_FAILED								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004D)
#define ERROR_SEND_BEGIN_EXPIRED_MSG_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004E)

//ncOracleTablesRestoreCommon.cpp
#define ERROR_CANNOT_FIND_TNSNAME_FILE								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004B)
#define ERROR_ORACLE_SELECT_TABLE_NOT_EXSITS						MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004C)
#define ERROR_ORACLE_SELECT_TABLE_DUPLICATED                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004D)
#define ERROR_GET_LOGIN_FAILED                                      MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004E)
#define ERROR_CURRENT_USER_AND_INSTALL_USER_NOT_SAME                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x004F)
#define ERROR_ORACLE_STAGE_PATH_NOLEGAL								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0050)
#define ERROR_ORACLE_STAGE_PATH_HAVE_OTHER_FILES					MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0051)
#define ERROR_ORACLE_SINGLE_TABLE_RESTORE_DBNAME_SAME				MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0052)
#define ERROR_ORAPWD_CREATE_PASSWORD_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0053)
#define ERROR_ORACLE_START_APP_FAILED								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0054)
#define ERROR_ORACLE_LISTENER_NO_SID_LIST                           MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0055)
#define ERROR_ORACLE_SYSTEM_SERVICE_NO_ENVIROMENT					MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0056)
//add last
#define ERROR_DATABASE_NOT_OPEN_STATUS                              MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0057)
#define ERROR_BEGSEQ_LARGER_THAN_CURRENT							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0058)
#define ERROR_CREATE_SHARE_MEM_FAILED                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0059)
#define ERROR_REMOVE_SHARE_MEM_FAILED                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x005A)
#define ERROR_SEND_ORA_DATA_MSG_OVER_FAILED                         MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x005B)
#define ERROR_RECIVE_ORA_DATA_MSG_OVER_FAILED                       MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x005C)
#define ERROR_FROK_FAIL																	MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x005D)
#define ERROR_INIT_FAIL																	MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x005E)
#define ERROR_UNKONWN_FAILED																	MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x005F)



// add ncOracleDatabasebManager.cpp
#define ERROR_ORACLE_DYLISTENER										MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x0062)


/**************************************************************************************************************************/
//ORACLEEngine Error 0x8000~0xBFFF
#define ERROR_START_ORACLE_SCHEDULE_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x8000)
#define ERROR_GET_BACKUP_TYPE_ERROR									MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x8001)
#define ERROR_ORACLE_DATA_SOURCE_CONTRACTID                         MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x8002)
#define ERROR_CREATE_ORACLE_BACKUP_SCHEDULER_FAILED                 MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x8003)
#define ERROR_CREATE_ORACLE_RETORE_SCHEDULER_FAILED                 MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0x8004)

//ORACLEDatascource Error 0xc000~0xFFFF
#define ERROR_INVALID_FUNCTION_ERROR								MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC000)
#define ERROR_GET_TABLESPACE_ERROR									MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC001)
#define ERROR_ARRAY_OUT_RANGE_ERROE									MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC002)
#define ERROR_NOT_ADD_ORACLE_INSTANCE                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC003)
#define ERROR_ADD_DATASOURCE_FAILED                                 MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC004)
#define ERROR_SAVE_SECDATA_ERROR                                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC005)
#define ERROR_GET_SECDATA_ERROR                                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC006)
#define ERROR_ADD_SECDATA_ERROR                                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC007)
#define ERROR_DELETE_INSTANCE_ERROR                                 MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC008)
#define ERROR_OPEN_SREVICES_MANAGER_FAILE                           MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC009)
#define ERROR_ENUM_SREVICES_STATUS_FAILE                            MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC00A)
#define ERROR_USERNAME_PASSWORD_ERROR                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC00B)
#define ERROR_ORACLE_ERROR                                          MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC00C)
#define ERROR_USERNAME_PASSWORD_NULL                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC00D)
#define ERROR_ORACLE_DATASOURCE_EMPTY                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC00E)
#define ERROR_CREATE_PROCESS_ERROR									MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC00F)
#define ERROR_ORACLE_INSTANCE_ARC_PROCESS_NO_STARTUP				MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC010)
#define ERROR_OPEN_CONFIG_FILE_FAILE                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC011)
#define ERROR_GET_FILE_LIST_EXCEPTION                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC012)
#define ERROR_READ_CONFIG_FILE_FAILE                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC013)
#define ERROR_ORACLE_DOUBLE_MACHINE_DATASOURCE_ERROR                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC014)
#define ERROR_INSTANCE_NOT_EXIST                                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC015)
#define ERROR_ORACLE_DATASOURCE_EXIST_CONFIG						MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC016)
#define ERROR_CHECK_DIR_PATH_ERROR									MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC017)
#define ERROR_GET_ORACLE_DATAFILE_FAILED							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC018)
#define ERROR_GET_CONTROL_FILE_FAILED				                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC019)
#define ERROR_GET_CONTROL_FILE_ERROR                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC01A)
#define ERROR_GET_ARCHIVELOG_FILE_FAILED                            MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC01B)
#define ERROR_GET_ARCHIVELOG_FILE_ERROR                             MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC01C)
#define ERROR_GET_TEMPFILE_FAILED                                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC01D)
#define ERROR_GET_TEMPFILE_ERROR                                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC01E)
#define ERROR_ARCHIVE_DEST_EMPTY						            MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC01F)
#define ERROR_RELATIVE_ARCHIVE_PATH				                    MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC020)
#define ERROR_ARCHIVE_DEST_NOSUPPORT                                MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC021)
#define ERROR_GET_ARCHIVELOG_FAILED                                 MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC022)
#define ERROR_GET_SPFILE_FAILED                                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC023)
#define ERROR_FILE_PATH_INVALID                                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC024)
#define ERROR_ORACLE_DATABASE_NOT_ARCHIVELOG_MODE                   MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC025)
#define ERROR_GET_SOURCE_PATH_FAILED						        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC026)
#define ERROR_GET_SOURCEPATHS_UNKOWN_ERROR							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC027)
#define ERROE_ORACLE_DATABASE_STATUS_ERROR							MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC028)
#define ERROR_ORACLE_DATABASE_LISTERNER_FILE_NOT_EXIST				MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC029)
#define ERROR_GET_INSTANCEINFO_FAILED                               MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC02A)
#define ERROR_ORACLE_CONSISTENCY_FAILED                             MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC02B)
#define ERROR_ORACLE_STOP_CONSISTENCY_FAILED                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC02C)
#define ERROR_ORACLE_CONNECT_INSTANCE_FAILED                        MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC02D)
#define ERROR_CAN_NOT_FIND_FILE                                     MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC02E)
#define ERROR_INSTANCE_NOT_VALID_FOR_BACKUP                         MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC02F)
#define ERROR_GETSIDFAIL											MAKE_ORACLE_BACK_ERROR_NUM (APP_ERROR_EXCEPTION, 0xC030)


#endif /* _NC_ORACLE_BACKUP_EXCEPTION_ */
